"""phasesweep: YAML-driven phase-chained hyperparameter sweeps."""

# Define ``__version__`` BEFORE importing submodules. Source of truth is the
# installed package metadata generated by setuptools-scm from SCM state.
from phasesweep._metadata import __version__

# Public API exports follow the ``__version__`` assignment by design. Keep the
# order stable so metadata is available before importing heavier subpackages.
from phasesweep.config import Experiment, load_experiment  # noqa: E402
from phasesweep.engine import (  # noqa: E402
    NoFeasibleTrialError,
    ProcessCleanupUncertainError,
    UnsafeProcessCleanupError,
    Winner,
    experiment_status,
    run_experiment,
)
from phasesweep.reporting import report_objective  # noqa: E402

__all__ = [
    "Experiment",
    "NoFeasibleTrialError",
    "ProcessCleanupUncertainError",
    "UnsafeProcessCleanupError",
    "Winner",
    "__version__",
    "experiment_status",
    "load_experiment",
    "report_objective",
    "run_experiment",
]
